<?php

return [
    'max_upload_kilobytes' => (int) env('PRINT_MAX_UPLOAD_KB', 20480),
    'max_copies' => (int) env('PRINT_MAX_COPIES', 20),
    'allowed_extensions' => [
        'pdf',
        'doc', 'docx',
        'xls', 'xlsx',
        'ppt', 'pptx',
        'txt', 'rtf',
        'jpg', 'jpeg', 'png', 'bmp', 'gif', 'tif', 'tiff', 'webp',
    ],
    'mime_types' => [
        'pdf' => 'application/pdf',
        'doc' => 'application/msword',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'xls' => 'application/vnd.ms-excel',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'ppt' => 'application/vnd.ms-powerpoint',
        'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'txt' => 'text/plain',
        'rtf' => 'application/rtf',
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'bmp' => 'image/bmp',
        'gif' => 'image/gif',
        'tif' => 'image/tiff',
        'tiff' => 'image/tiff',
        'webp' => 'image/webp',
    ],
    'offline_after_seconds' => (int) env('PRINTER_OFFLINE_AFTER_SECONDS', 90),
    'development_admin_password' => env('DEV_ADMIN_PASSWORD'),
];
