<x-app-layout>
    <x-slot name="header"><h1 class="text-2xl font-bold">Upload Document or Image</h1><p class="mt-1 text-sm text-slate-500">Supported office documents and images are stored privately.</p></x-slot>
    <form method="POST" action="{{ route('print-jobs.store') }}" enctype="multipart/form-data" class="mx-auto max-w-2xl space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
        @csrf
        <div><x-input-label for="document" value="Document or Image" /><input id="document" name="document" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.rtf,.jpg,.jpeg,.png,.bmp,.gif,.tif,.tiff,.webp" required class="mt-2 block w-full rounded-xl border border-slate-300 p-3 text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-cyan-50 file:px-4 file:py-2 file:font-semibold file:text-cyan-700" /><x-input-error :messages="$errors->get('document')" class="mt-2" /><p class="mt-2 text-xs leading-5 text-slate-500">PDF, Word, Excel, PowerPoint, text, RTF, JPG, PNG, BMP, GIF, TIFF or WebP. Maximum: <x-file-size :bytes="config('printing.max_upload_kilobytes') * 1024" /></p></div>
        <div><x-input-label for="printer_id" value="Printer" /><select id="printer_id" name="printer_id" required class="mt-1 block w-full rounded-xl border-slate-300 focus:border-cyan-500 focus:ring-cyan-500"><option value="">Select a printer</option>@foreach ($printers as $printer)<option value="{{ $printer->id }}" @selected(old('printer_id') == $printer->id)>{{ $printer->name }}{{ $printer->location ? ' — '.$printer->location : '' }} ({{ $printer->displayedStatus()->value }})</option>@endforeach</select><x-input-error :messages="$errors->get('printer_id')" class="mt-2" /></div>
        <div><x-input-label for="copies" value="Copies" /><x-text-input id="copies" name="copies" type="number" min="1" :max="config('printing.max_copies')" :value="old('copies', 1)" required class="mt-1 block w-full" /><x-input-error :messages="$errors->get('copies')" class="mt-2" /></div>
        <div class="flex justify-end gap-3"><a href="{{ route('print-jobs.index') }}" class="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</a><button class="rounded-xl bg-cyan-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700">Submit Print Job</button></div>
    </form>
</x-app-layout>
